# Generated by Django 2.1.7 on 2019-02-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanhanhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Report',
        ),
    ]
