# Generated by Django 2.1.7 on 2019-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanhanhas', '0002_auto_20190223_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='topics',
            field=models.CharField(default='pol;kay;sign;feck;mom', max_length=300),
            preserve_default=False,
        ),
    ]
