# Generated by Django 2.1.7 on 2019-02-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanhanhas', '0003_report_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='topics',
        ),
    ]
